collective: intellij-rainbow-brackets
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: "Hey <author> , thanks for supporting us on Open Collective :heart::heart::heart: We'll give a special attention to this issue!"
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue/feature request. We will get back to you as soon as we can.
  Also, check out our <link> and consider backing us - every little helps!

  PS.: We offer `priority` support for all backers. Don't forget to
  add `priority` label when you start backing us :smile:
